# Configuração Streamlit
[server]
headless = true
enableCORS = false
port = 8501  # Número fixo. NÃO use $PORT no TOML

[theme]
primaryColor = "#1a73e8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

